name: Run Lint, Test and Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run coverage
      - run: npm run lint && npm run test && npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

